### ISSUE TITLE
automating the process of LVMerge

### ISSUE THREAD

**Issue by yuvaforlife** [joerg/LabViewGitEnv#1] opened 2013-10-03 15:24 UTC
How do i automate the process of running LVMerge.exe without running manually.
I am using Git Extensions. The LVCompare runs fine. Kindly help me!!

**Comment by joerg** [comment] 2013-10-03 15:53
Hi. Running LVMerge and LVCompare manually should never be necessary. The Problem is that most GUI Tools can not use the merge and compare settings of GIT, but most have their own settings hidden somewhere.
First off, I'd check if everything is installed and set up correctly. Try running a "git diff" and a "git merge" in your console and see if LabView fires up the way it is supposed to do.
Now, check if GitExtensions has a Compare and Merge setting somewhere. Maybe ask the author of that programme if you can't find anything. If it does you will need to configure this one. As I do not know GitExtensions I can't help you with that, but I am sure it can't be that hard. Most possibly you will have to direct GitExtensions to the LVMerge.exe and pass the correct parameters.
If you get it working please send me what you had to do and I will update the readme.

P.S.: Here is a similar problem. Hope it helps: http://stackoverflow.com/questions/2468230/how-to-use-winmerge-with-git-extensions

**Comment by joerg** [comment] 2013-10-11 13:20
Since this is now more than a week old and it is not really a bug I am closing this. If you still have problems please post some error messages and an exact description of what you did to run into that error.

**Closed as completed by joerg** 2013-10-11 13:20 UTC
